/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facebook_hadoop;

import java.io.IOException;

import org.apache.hadoop.fs.Path;
import org.apache.hadoop.mapreduce.Mapper;
import org.apache.hadoop.mapreduce.Reducer;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;

import facebook_hadoop.pipeline.Annotation;
import facebook_hadoop.pipeline.VnCoreNLP;

public class App {
    private static VnCoreNLP pipeline;

    public static class DataExtractionMapper extends Mapper<Object, Text, Text, IntWritable> {

        private final static IntWritable one = new IntWritable(1);

        public void map(Object ikey, Text ivalue, Context context)
                throws IOException, InterruptedException {
            String row = ivalue.toString();
            String[] cells = row.split(",(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
            try {
                String raw_text = cells[7];
                Annotation annotation = new Annotation(raw_text);
                pipeline.annotate(annotation);
                String[] results = annotation.toString().split(" ");
                for (String item : results) {
                    context.write(new Text(item), one);
                }

            } catch (Exception ex) {
            }
        }
    }

    public static class DataExtractionReducer extends Reducer<Text, IntWritable, Text, IntWritable> {
        private final static IntWritable result = new IntWritable();

        public void reduce(Text key, Iterable<IntWritable> values, Context context)
                throws IOException, InterruptedException {
            int sum = 0;
            for (IntWritable val : values) {
                sum += val.get();
            }
            result.set(sum);
            context.write(key, result);
        }
    }

    public static void main(String[] args) throws Exception {
        pipeline = new VnCoreNLP(new String[] { "wseg" });
        Configuration conf = new Configuration();
        Job job = Job.getInstance(conf, "Facebook extraction");
        job.setJarByClass(App.class);
        job.setMapperClass(DataExtractionMapper.class);
        job.setReducerClass(DataExtractionReducer.class);
        job.setOutputKeyClass(Text.class);
        job.setOutputValueClass(IntWritable.class);
        FileInputFormat.addInputPath(job, new Path(args[0]));
        FileOutputFormat.setOutputPath(job, new Path(args[1]));
        System.exit(job.waitForCompletion(true) ? 0 : 1);
    }
}
